[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "merge balance meat amused senior vendor blur stadium wonder arrive brain deliver hazard family burst brass outdoor feature flower disease already round air imitate"
